currency.mapping = {
  AT = ["euro|EUR|€"]
  BE = ["euro|EUR|€"]
  BG = ["bulgarianLev|BGN|лв"]
  IC = ["euro|EUR|€"]
  XI = ["euro|EUR|€"]
  HR = ["kuna|HRK|kn"]
  CY = ["euro|EUR|€"]
  CZ = ["czechKoruna|CZK|Kč"]
  DK = ["danishKrone|DKK|kr"]
  EE = ["euro|EUR|€", "estonianKroon|EEK|kr"]
  FI = ["euro|EUR|€"]
  FR = ["euro|EUR|€"]
  DE = ["euro|EUR|€"]
  EL = ["euro|EUR|€"]
  HU = ["forint|HUF|ft"]
  IE = ["euro|EUR|€"]
  IT = ["euro|EUR|€"]
  LV = ["euro|EUR|€"]
  LT = ["euro|EUR|€"]
  LU = ["euro|EUR|€"]
  MT = ["euro|EUR|€"]
  XJ = ["euro|EUR|€"]
  MC = ["euro|EUR|€"]
  NL = ["euro|EUR|€"]
  PL = ["zloty|PLN|zł"]
  PT = ["euro|EUR|€"]
  RO = ["newLeu|RON|ei"]
  SK = ["euro|EUR|€"]
  SI = ["euro|EUR|€"]
  ES = ["euro|EUR|€"]
  SE = ["swedishKrona|SEK|kr"]
}